### ISSUE TITLE
Hello Sir

### ISSUE THREAD

**Issue by Pocker88** [videoearn/videoearner#1]
Very high price... I'm currently collecting 5$ in a week or so.....

**Comment by videoearn** [comment]
Hello,
The linux version is free.
Only windows extension is one time paid.
Its due to the demand and complexity of the project, the price was set.
You may not find similar scripts online published yet. 

Thank you

**Comment by videoearn** [comment]
Although it takes time to recover the investment, you can get about $0.5 per day by using all of them. So, it takes about 10 days to recover the investment made if you use one account. 

Thank you

**Comment by videoearn** [comment]
Price has been discounted to $1 now as free captchas are not available to users from cap.guru
Thank you

**Comment by Pocker88** [comment]
1$ its normal price thx.

**Comment by FMDose89** [comment]
Do u have FAUCETPAY wallet???
I can send LTC

**Comment by videoearn** [comment]
If faucetpay is not working, please transfer to payeer wallet and then make the payment.
