### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by FMDose89** [videoearn/videoearner#2]
Hello Sir can u give me your wallet adress FAUCETpay I will send u cash for thiw script... 
coz I have some issue with payments system on site.

**Comment by videoearn** [comment]
Hello,
The payment gateway is working fine. There is no issue. You have to make exact payment. 
If there is any issue, please share the screenshot. 

Thank you

**Comment by FMDose89** [comment]
![Screenshot_8](https://github.com/videoearn/videoearner/assets/135632275/8c344310-2006-4695-8784-2ad743619482)

**Comment by FMDose89** [comment]
Pls sir give me your facuetpay adress I send u money - thats all) 
Its so simply

**Comment by videoearn** [comment]
Unfortunately, we do not accept other payment methods. Please transfer to payeer wallet and then make payment if there is an issue. 

Thank you
