### ISSUE TITLE
Hello Sir question about captcha

### ISSUE THREAD

**Issue by FMDose89** [videoearn/videoearner#3]
How can I change the captcha service?
I have a more favorable service
I have AРI

**Comment by videoearn** [comment]
Hello,
If the captcha service has same url paths as cap.guru api then you can change that in windows hosts file to point to the IP address of the new captcha solver.
If your IP address of new solver is 34.5.5.34 then you will have to update your hosts file in windows as mentioned below.
Hosts file in windows is mentioned in the following path c:\Windows\System32\Drivers\etc\hosts
```
34.5.5.34  api.cap.guru
```

Similarly this has to be changed  in /etc/hosts file if you are using linux OS.

Thank you

**Comment by videoearn** [comment]
You have to check with the respective captcha solver to see if the APIs are similar.

**Comment by FMDose89** [comment]
I have now :
IP address Xevil 
Url address Xevil
and API key 
how can I use it in script?

**Comment by videoearn** [comment]
Hello,
As mentioned earlier, you can use it as long as Xevil sends you coordinates similar to cap.guru.
Please try replacing hosts file as mentioned above. 

Thank you

**Comment by videoearn** [comment]
The latest file has open source code for content.js. You can modify the script accordingly.

Thank you

**Comment by FMDose89** [comment]
Thhank u so much!

**Comment by FMDose89** [comment]
I cant change this mess (--silent-debugger-extension-api) on chrome 
how fix it????

**Comment by videoearn** [comment]
Did you give a space before --silent?
