### ISSUE TITLE
WHAT IS WRONG ?!?

### ISSUE THREAD

**Issue by FMDose89** [videoearn/videoearner#4]
Your extension does not work. I open a page of the site where there is a button to start browsing and - nothing. I press the extension button on the YOUTUBE button by hand. It does nothing else. I waited for two minutes and three . It doesn’t do anything it doesn’t work so what conclusion does it suggest?!? I think you know. I did everything because it is written in the instructions that you have attached to the archive. everything was done with the browser and with the key and so on. and NOTHING works... 

When the timer on the preview ends then the extension does not CLICK NEXT. and the site automatically switches to YOUTUBE video. and then you need to manually cut the YouTube tab to go to the site and reinstall the video.

![Screenshot_4](https://github.com/videoearn/videoearner/assets/135632275/932a0aed-bb42-4ff5-beef-9f47dd892619)
![Screenshot_5](https://github.com/videoearn/videoearner/assets/135632275/f73fbb0f-fbdd-43da-9f89-70678840c1f9)

**Comment by videoearn** [comment]
Hello,
Due to the website changes, it was not working. The timer has been reduced now.
Please replace the entire code in your content.js file with the attached file.

[Deleted]
Thank you

**Comment by FMDose89** [comment]
there are more errors after 3-4 clicks on the play youtube button the script stops working ... just hangs and stands still.
![Screenshot_1](https://github.com/videoearn/videoearner/assets/135632275/06a8bbba-f489-402e-9d71-70b75a4e96ab)

**Comment by videoearn** [comment]
Hello,
Please install ublock origin and Reject Service worker extension if there are background js running.
It works fine here without issues. Also make sure you don't have other extensions installed and don't switch windows or tabs. 
If you switch to different window or tab it may stop clicking.

You have to create new profile in chrome if you wish to do any other task.

https://chromewebstore.google.com/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm

https://chromewebstore.google.com/detail/reject-service-worker/falajmifjcihbmlokgomiklbfmgmnopd

Thank you

**Comment by videoearn** [comment]
If there are any errors please share the screenshot.

Thank you

**Comment by videoearn** [comment]
Few optimizations were made to the script. Please replace the content in content.js file. If new window is opening in youtube immediately, try to maximize the browser to identify the coordinates correctly. 

[Deleted]

**Comment by FMDose89** [comment]
![Screenshot_8](https://github.com/videoearn/videoearner/assets/135632275/250b5c14-6600-4909-8bd5-5bf08737852a)

Hello SIr - Sometimes this button as shown on the screenshot lead to an error in the script + some bugs in the form of (4-5 views and then pause on), just waiting or viewing and not clicking further after which the site goes to the YouTube site and you need to manually close YouTube and turn everything on again.

**Comment by videoearn** [comment]
Hello,
You have to resize the window accordingly so that it does not click there.
Please find the updated script. This will close youtube windows if it opens. 



[Deleted]

Thank you

**Comment by FMDose89** [comment]
> Hello, You have to resize the window accordingly so that it does not click there. Please find the updated script. This will close youtube windows if it opens.
> 
> [Deleted]
> 
> Thank you

Sir need your help .... they change AGAIN((( 
![Screenshot_6](https://github.com/videoearn/videoearner/assets/135632275/4dd1424b-a7c9-463a-9a46-cb3e3d3e1155)

**Comment by videoearn** [comment]
Please find the attachment for the updated script.

[content.txt](https://github.com/videoearn/videoearner/files/14969232/content.txt)

Thank you

**Comment by FMDose89** [comment]
> Please find the attachment for the updated script.

Where Sir??? How find....

**Comment by videoearn** [comment]
Hello, 
The link is mentioned in the previous comment. You have to replace the contents in content.js file with the attached file.

![image](https://github.com/videoearn/videoearner/assets/159670470/192f6c0d-fdd9-483d-8ada-0e7fa9bddb8f)


Thank you

**Comment by FMDose89** [comment]
> Hello, The link is mentioned in the previous comment. You have to replace the contents in content.js file with the attached file.
> 
> ![image](https://private-user-images.githubusercontent.com/159670470/322265044-192f6c0d-fdd9-483d-8ada-0e7fa9bddb8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjczNjEsIm5iZiI6MTcxMzE2NzA2MSwicGF0aCI6Ii8xNTk2NzA0NzAvMzIyMjY1MDQ0LTE5MmY2YzBkLWZkZDktNDgzZC04YWRhLTBlN2ZhOWJkZGI4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQwNzQ0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Y2Y1NzNhYzE2YTg5OTZjZGFhYzU1MTY0YmY3MTI4YmY1NjQ2ZDM3MDkyYTJjYjQwN2EzNzcwMGI1ODc4Y2VlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sy2Y67zxWhXIvmSYf_t4ow-BNFacLt7mrcYycrXJT-4)
> 
> Thank you

Oooo Ok. I think u mean in other menu (of this site). Than u so much.
Iam so sorry.
