### ISSUE TITLE
I sent the amount twice and did not receive the extension.

### ISSUE THREAD

**Issue by monkeyde98** [videoearn/videoearner#5]
This is the hash of the first purchase
9b9e53fe3fac2088a1d85abe506e7f5013c62abe5653f53a8efe76f713b8978c
 and this is the one for the second purchase.
15e0eff49efb9935816b60e9abc114cb633be384be8943660dd551d48962a41c

**Comment by videoearn** [comment]
Hello,
You have to send exact amount as mentioned in the website. The payment system does not accept invalid amount.
I am sending you link here and will be deleting the comment. Check your email.


Thank you

**Comment by videoearn** [comment]
Link for download. Expires in one hour.

https://tmpfiles.org/4631090/video_earn_script.zip

**Comment by videoearn** [comment]
Link has been sent in the previous comment and deleted. Please check your email.

**Comment by monkeyde98** [comment]
I didn't find the link.

**Comment by videoearn** [comment]
Please check the above comment. It will be deleted after 2 minutes.

**Comment by monkeyde98** [comment]
I achieved.

**Comment by videoearn** [comment]
The price is discounted to $1 when it was initially set to $5.

**Comment by videoearn** [comment]
Please mention your wallet address for refund of remaining amount. Mention the amount and your wallet address to receive your extra amount deposited. Transaction fee will be deducted according to LTC payment network while refunding. 


Thank you

**Comment by monkeyde98** [comment]
address. MJUpFFDVHXnhDncnTbWvDBoFb5sBoyo5o8
 value 0.011

Do you have a tip for working with multiple accounts?

**Comment by videoearn** [comment]
Well you are supposed to use only once account. You can create different chrome profiles for different websites.

**Comment by videoearn** [comment]
Sent 0.011 to MJUpFFDVHXnhDncnTbWvDBoFb5sBoyo5o8

Transaction ID: f3b8f27871d48c9cf57e7d7116a5c53ef8acd2e6aac03b50ae12af893bb9dd90

Thank you

**Comment by videoearn** [comment]
Closing this as script has been sent and amount has been refunded.

**Comment by monkeyde98** [comment]
How do I get the updated version of the extension? whenever it is updated?
Is it possible to use Solver Captcha TG API instead of Captchaguru?
bux.money closes after watching a video.

**Comment by videoearn** [comment]
Hello,
At the moment, it is mentioned in ReadMe file. Please find the link below.

https://github.com/videoearn/videoearner#prerequisites

Thank you
