### ISSUE TITLE
Updated

### ISSUE THREAD

**Issue by monkeyde98** [videoearn/videoearner#6]
How do I get the updated version of the extension? whenever it is updated?
Is it possible to use Solver Captcha TG API instead of Captchaguru?
bux.money closes after watching a video.

**Comment by videoearn** [comment]
Hello,
Please replace your content.js file with the contents in the following file.

https://github.com/videoearn/videoearner/files/14969232/content.txt


Yes, it is possible to use other captcha solvers but the code has to be modified to do so which we do not plan to do it right away. We will plan to do it after careful consideration. 

Thank you

**Comment by monkeyde98** [comment]
The bux.money and worker.cash script does not resolve the captcha.  is there anything that can be done?

**Comment by videoearn** [comment]
Hello,
For worker.cash and bux.money, the recognition is not good from the captcha solving service. 
If the response from the captcha solver is received, it will solve the captcha. 

Thank you

**Comment by monkeyde98** [comment]
How do I get the updated version of the extension?
